development:
  adapter: mysql
  database: tasche_dev
  username: root
  password: 

test:
  adapter: mysql
  database: tasche_test
  username: root
  password:

production:
  adapter: mysql
  database: tasche_prod
  username: root
  password:
